# Generated by Django 4.2.11 on 2024-04-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ingredients_ingredient_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeTags',
            new_name='RecipeTag',
        ),
    ]
