# Generated by Django 4.2.11 on 2024-04-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_recipe_created_at_alter_recipe_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppigcart',
            old_name='user_id',
            new_name='user',
        ),
    ]
