# Generated by Django 4.2.11 on 2024-04-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_id_shoppigcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppigcart',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.AlterUniqueTogether(
            name='shoppigcart',
            unique_together={('user', 'recipe')},
        ),
    ]
