# Generated by Django 4.2.11 on 2024-04-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_recipe_id_shoppigcart_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='id_user',
            new_name='user',
        ),
    ]
