# Generated by Django 4.2.11 on 2024-04-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_id_recipe_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('subscriber', 'subscrib_to')},
        ),
    ]
