volumes:
  pg_data:
  static_all:
  media_volume:
  certbot_root:
  ssl_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: alenkas/foodgram_frontend
    env_file: .env
    depends_on:
      - db
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_all:/app/result_build/
  backend:
    image: alenkas/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_all:/backend_static/
      - media_volume:/app/media/
  nginx:
    image: alenkas/foodgram_gateway
    env_file: .env
    volumes:
      - static_all:/usr/share/nginx/html/
      - media_volume:/usr/share/nginx/html/media/
      - certbot_root:/var/www/certbot/:ro
      - ssl_volume:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
  certbot:
    image: alenkas/certbot:latest
    volumes:
      - certbot_root:/var/www/certbot/:rw
      - ssl_volume:/etc/letsencrypt/:rw